included:
  - Sources
  - Tests
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - closure_end_indentation
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - first_where
  - implicit_return
  - modifier_order
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - sorted_first_last
disabled_rules:
  - identifier_name
  - private_over_fileprivate
line_length:
  warning: 200
  error: 250
nesting:
  type_level:
    warning: 2
trailing_whitespace:
  ignores_empty_lines: true

