name: CI

on: [push]

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
   
jobs:
  ci:
    name: Lint, Build, Analyze, Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: |
          set -o pipefail
          swiftlint lint --strict --quiet | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 title=Lint error,file=\1,line=\2,col=\3::\5\n\1:\2:\3/'
      - name: Build
        run: xcodebuild -scheme SwiftTest  -destination 'platform=macos'
      - name: Analyze
        run: |
           set -o pipefail
           xcodebuild -scheme SwiftTest  -destination 'platform=macos' > xcodebuild.log
           swiftlint analyze --strict --quiet | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 title=Lint error,file=\1,line=\2,col=\3::\5\n\1:\2:\3/'
      - name: Test
        run: xcodebuild test -scheme SwiftTest  -destination 'platform=macos'
