name: CI

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
   
jobs:
  ci:
    name: Lint, Analyze, Test
    runs-on: macos-latest
    env:
      BUNDLE: SwiftTest.bundle
      BUCKET_PATH: ""
      VERSION: ""

    steps:
      - uses: actions/checkout@v3
      - name: Configure Environment
        run: |
          echo "Setting vars..."
          export VERSION=$(git describe --dirty --tags --abbrev=10 --always --dirty)
          export BUCKET_PATH="TheJumpCloud/jumpcloud-mac-loginwindow/${VERSION}/${BUNDLE}.tgz"
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
          echo "BUCKET_PATH=${BUCKET_PATH}" >> "$GITHUB_ENV"
          echo "Version is: ${VERSION}"
          echo "Configuration complete!"
      - name: Lint
        run: |
          set -o pipefail
          swiftlint lint --quiet | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 title=Lint error,file=\1,line=\2,col=\3::\5\n\1:\2:\3/'
      - name: Analyze
        run: |
           set -o pipefail
           xcodebuild analyze -verbose -scheme SwiftTest -destination 'platform=macos' | tee -a xcodebuild.log | xcpretty
           echo "running swiftlint analyze..."
           swiftlint analyze --compiler-log-path xcodebuild.log --strict --quiet | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 title=Lint error,file=\1,line=\2,col=\3::\5\n\1:\2:\3/'
      - name: Test
        run: |
           set -o pipefail
           xcodebuild test -scheme SwiftTest -destination 'platform=macos' | xcpretty
