name: Version Check

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_pr_labels:
    name: Verify that the PR has a valid label
    runs-on: ubuntu-latest
    env:
      LABEL: ""
      LABEL_COUNT: 0
      PR_LABEL_LIST: ${{ toJson(github.event.pull_request.labels.*.name) }}
      ISSUE_LABEL_LIST: ${{ toJson(github.event.issue.labels.*.name) }}
    steps:
      - name: Get Current Labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -H "Accept: application/vnd.github+json" /repos/afeick/swift-test/issues/${{ github.event.pull_request.number }}/labels | jq '[.[].name]'
          LABEL_RESPONSE_NAMES=$(gh api -H "Accept: application/vnd.github+json" /repos/afeick/swift-test/issues/${{ github.event.pull_request.number }}/labels | jq '[.[].name]')
          echo $LABEL_RESPONSE_NAMES
      - name: Major
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: |
          LABEL_COUNT=$((LABEL_COUNT+1))
          echo "LABEL_COUNT=${LABEL_COUNT}" >> "$GITHUB_ENV"
          echo "LABEL='major'" >> "$GITHUB_ENV"
      - name: Minor
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: |
          LABEL_COUNT=$((LABEL_COUNT+1))
          echo "LABEL_COUNT=${LABEL_COUNT}" >> "$GITHUB_ENV"
          echo "LABEL='minor'" >> "$GITHUB_ENV"
      - name: Patch
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: |
          LABEL_COUNT=$((LABEL_COUNT+1))
          echo "LABEL_COUNT=${LABEL_COUNT}" >> "$GITHUB_ENV"
          echo "LABEL='minor'" >> "$GITHUB_ENV"
      - name: No Version
        if: contains(github.event.pull_request.labels.*.name, 'no version')
        run: |
          LABEL_COUNT=$((LABEL_COUNT+1))
          echo "LABEL_COUNT=${LABEL_COUNT}" >> "$GITHUB_ENV"
          echo "LABEL='no version'" >> "$GITHUB_ENV"
      - name: Version Label
        if: env.LABEL_COUNT == 1
        run: |
          echo "::notice::Version label is: ${LABEL}"
      - name: No Version Label
        if: env.LABEL_COUNT < 1
        run: |
          echo "::error::No version label detected! PRs require one of the follow labels: major, minor, patch, no version"
          exit -1
      - name: Multiple Version Labels
        if: env.LABEL_COUNT > 1
        run: |
          echo "::error::Too many versions detected! PRs require one of the follow labels: major, minor, patch, no version"
          exit -1
